<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>515baabe-a563-46a3-a2bf-c222568b0896</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.0.2" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.15.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UserESBusinessLayer\UserESBusinessLayer.csproj" />
    <ProjectReference Include="..\UserESDataLayer\UserESDataLayer.csproj" />
  </ItemGroup>

</Project>
